### ISSUE TITLE
Plugin does not compile under Debian Jessie

### ISSUE THREAD

**Issue by mase76** [louisbraun/softhddevice-openglosd#1]
hi!
Since the latest changes for libavcodec in Debian Jessie, softhddevice does not compile
any more.

In file included from openglosd.h:44:0,
                 from softhddevice.cpp:41:
video.h: At global scope:
video.h:63:13: error: use of enum ‘PixelFormat’ without previous declaration
 extern enum PixelFormat Video_get_format(VideoHwDecoder _, AVCodecContext *,
             ^
video.h:64:16: error: use of enum ‘PixelFormat’ without previous declaration
     const enum PixelFormat *);
                ^
video.h:64:30: error: invalid type in declaration before ‘;’ token
     const enum PixelFormat *);
                              ^
In file included from softhddevice.cpp:50:0:
video.h:63:13: error: use of enum ‘PixelFormat’ without previous declaration
 extern enum PixelFormat Video_get_format(VideoHwDecoder *, AVCodecContext *,
             ^
video.h:64:16: error: use of enum ‘PixelFormat’ without previous declaration
     const enum PixelFormat *);
                ^
video.h:64:30: error: invalid type in declaration before ‘;’ token
     const enum PixelFormat *);
                              ^
In file included from softhddevice.cpp:1663:0:
/usr/local/src/vdr-2.2.0/include/vdr/receiver.h:29:30: warning: unused parameter ‘On’ [-Wunused-parameter]
   virtual void Activate(bool On) {}
                              ^
<builtin>: recipe for target 'softhddevice.o' failed
make[1]: *_\* [softhddevice.o] Error 1

**Comment by louisbraun** [comment]
Hi,

just apply the patch postet here:

http://www.vdr-portal.de/board16-video-disk-recorder/board55-vdr-plugins/p1272518-softhddevice-broken-after-system-update/#post1272518

In general this is a softhddevice issue...so Johns should care about that. Just because i've developed the OpenGL OSD extension, i'm not responsible for the complete plugin ;)

Cheers Louis
