### ISSUE TITLE
Does work with Vaapi

### ISSUE THREAD

**Issue by Mr-undead** [louisbraun/softhddevice-openglosd#3]
i have intel HD 4000. Does work this plugin with Vaapi?.

**Comment by louisbraun** [comment]
Hi,

no, only NVidia Cards are supported. 

In general the extension is pure OpenGL, but i use the OpenGL-VDPAU Interop Feature which is NVidia only. If somebody would adapt this small part (putting the generated OSD surface in an VAAPI rendered TV picture) then it would also work with VAAPI.

Cheers Louis
